### PR TITLE
Code cleaning

### PR DESCRIPTION
**Pull request by lucasgaspar**
Update the code to use the latest Unity conventions and changed the way the GestureDataset recalculates the patterns to be more efficient

https://github.com/amco/unity-gesture-recognizer/issues/6

### CODE REVIEW

**Review by giovas17 — APPROVED** [review]
No comments, looks good

**Review by anaisrmzl — APPROVED** [review]
:shipit:

**Review by SrTartarus — APPROVED** [review]
:shipit:

**Review by Horothenic — APPROVED** [review]
:shipit:

**Pull request merged**
